//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XT.Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.homely.vn;User ID=sa;Password=1234567")]
        public string apms_homely_vnConnectionString {
            get {
                return ((string)(this["apms_homely_vnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.homely.vn_demo_1;Persist Security Info=" +
            "True;User ID=sa;Password=1234567;MultipleActiveResultSets=True")]
        public string apms_homely_vn_demo_1ConnectionString {
            get {
                return ((string)(this["apms_homely_vn_demo_1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.cocome.vn_4;Persist Security Info=True;" +
            "User ID=sa;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_4ConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.cocome.vn_5;Persist Security Info=True;" +
            "User ID=sa;Password=1234567;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_5ConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.cocome.vn_server;Persist Security Info=" +
            "True;User ID=sa;Password=1234567;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_serverConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_serverConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUONG-PC;Initial Catalog=apms.cocome.vn_server_final;Persist Security" +
            " Info=True;User ID=sa;Password=1234567;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_server_finalConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_server_finalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-MO33L1P;Initial Catalog=apms.cocome.vn_official;Integrated Se" +
            "curity=True;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_server_final_aahcmConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_server_final_aahcmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-MO33L1P;Initial Catalog=apms.cocome.vn_official;Integrated Se" +
            "curity=True;MultipleActiveResultSets=True")]
        public string apms_cocome_vn_officialConnectionString {
            get {
                return ((string)(this["apms_cocome_vn_officialConnectionString"]));
            }
        }
    }
}
