// <auto-generated />
namespace XT.Model.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditTable_Faculty_Nickname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTable_Faculty_Nickname));
        
        string IMigrationMetadata.Id
        {
            get { return "201708090839551_EditTable_Faculty_Nickname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
